import { SUPER_ADMIN_EMAIL } from './firebase-config.js';
import { auth, db, hasConfig } from './firebase-core.js';
import { onAuthStateChanged, signOut, createUserWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { collection, getDocs, doc, getDoc, setDoc, updateDoc, deleteDoc, addDoc, serverTimestamp, query, orderBy, limit } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { sendEmail } from './email-service.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let me, meData={}, users=[], charts={};
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function toast(t,bad=false){const e=$('#toast');e.textContent=t;e.className='toast show'+(bad?' error':'');setTimeout(()=>e.classList.remove('show','error'),2600)}
function safe(v){return String(v??'').replace(/[<>&]/g,s=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[s]))}
async function log(action,meta={}){try{await addDoc(collection(db,'auditLogs'),{uid:me?.uid,email:me?.email,action,meta,createdAt:serverTimestamp()})}catch(_){}}
function isSuper(){return meData.role==='super_admin'||me?.email?.toLowerCase()===SUPER_ADMIN_EMAIL.toLowerCase()}
function showPage(id){$$('.section').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===id));$('#pageTitle').textContent=$(`[data-page="${id}"]`)?.textContent||id;if(innerWidth<760)$('#sidebar').classList.remove('open')}
async function colSum(userId,name){try{const snap=await getDocs(query(collection(db,'users',userId,name),limit(300)));return snap.docs.reduce((a,d)=>a+Number(d.data().amount||0),0)}catch{return 0}}
async function loadUsers(){try{const snap=await getDocs(query(collection(db,'users'),orderBy('createdAt','desc')));users=snap.docs.map(d=>({id:d.id,...d.data()}));await Promise.all(users.map(async u=>{u.totalIncome=await colSum(u.id,'income');u.totalExpenses=await colSum(u.id,'expenses');u.totalSavings=u.totalIncome-u.totalExpenses;}));renderAll()}catch(e){toast(e.message,true)}}
function renderCards(){const total=users.length,pending=users.filter(u=>u.status==='pending').length,active=users.filter(u=>u.status==='active').length,inc=users.reduce((a,u)=>a+u.totalIncome,0),exp=users.reduce((a,u)=>a+u.totalExpenses,0),sav=inc-exp;$('#adminCards').innerHTML=[['Total Users',total],['Pending Approvals',pending],['Active Users',active],['Total Income',money(inc)],['Total Expenses',money(exp)],['Total Savings',money(sav)]].map(x=>`<div class="card glass"><h3>${x[0]}</h3><div class="value">${x[1]}</div><span class="badge active">Live</span></div>`).join('')}
function statusBadge(u){return `<span class="badge ${safe(u.status||'pending')}">${safe(u.status||'pending')}</span>`}
function created(u){return u.createdAt?.toDate?u.createdAt.toDate().toLocaleDateString():''}
function renderApprovals(){const rows=users.filter(u=>u.status==='pending'||u.approved===false);$('#approvalTable').innerHTML='<thead><tr><th>Name</th><th>Email</th><th>Registration Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+ (rows.map(u=>`<tr><td>${safe(u.name)}</td><td>${safe(u.email)}</td><td>${created(u)}</td><td>${statusBadge(u)}</td><td><button class="btn primary" onclick="window.approveUser('${u.id}')">Approve</button> <button class="btn danger" onclick="window.rejectUser('${u.id}')">Reject</button></td></tr>`).join('')||'<tr><td colspan="5">No pending approvals</td></tr>')+'</tbody>'}
function renderUsers(){const q=$('#userSearch')?.value?.toLowerCase()||'',f=$('#userFilter')?.value||'';const arr=users.filter(u=>(!f||u.status===f)&&JSON.stringify(u).toLowerCase().includes(q));$('#usersTable').innerHTML='<thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Income</th><th>Expenses</th><th>Actions</th></tr></thead><tbody>'+ (arr.map(u=>`<tr><td>${safe(u.name)}</td><td>${safe(u.email)}</td><td>${safe(u.role)}</td><td>${statusBadge(u)}</td><td>${money(u.totalIncome)}</td><td>${money(u.totalExpenses)}</td><td><button class="btn" onclick="window.viewUser('${u.id}')">View</button> <button class="btn" onclick="window.toggleUser('${u.id}')">${u.status==='active'?'Deactivate':'Activate'}</button> <button class="btn danger" onclick="window.deleteUserRow('${u.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No users found</td></tr>')+'</tbody>'}
async function renderAudit(){const snap=await getDocs(query(collection(db,'auditLogs'),orderBy('createdAt','desc'),limit(120))).catch(()=>({docs:[]}));const logs=snap.docs.map(d=>d.data());$('#auditTable').innerHTML='<thead><tr><th>Date</th><th>User</th><th>Action</th><th>Meta</th></tr></thead><tbody>'+ (logs.map(l=>`<tr><td>${l.createdAt?.toDate?l.createdAt.toDate().toLocaleString():''}</td><td>${safe(l.email||l.uid)}</td><td>${safe(l.action)}</td><td>${safe(JSON.stringify(l.meta||{}))}</td></tr>`).join('')||'<tr><td colspan="4">No audit logs</td></tr>')+'</tbody>'}
function chart(id,type,labels,data,label='Count'){const el=$('#'+id);if(!el||!window.Chart)return;charts[id]?.destroy();charts[id]=new Chart(el,{type,data:{labels,datasets:[{label,data,borderWidth:2,tension:.35}]},options:{responsive:true,scales:type==='pie'||type==='doughnut'?{}:{y:{beginAtZero:true}}}})}
function renderCharts(){const labels=users.map(u=>(u.name||u.email||'User').slice(0,12));chart('userGrowth','line',labels,users.map((_,i)=>i+1));chart('platformFinance','bar',['Income','Expenses','Savings'],[users.reduce((a,u)=>a+u.totalIncome,0),users.reduce((a,u)=>a+u.totalExpenses,0),users.reduce((a,u)=>a+u.totalSavings,0)]);const reg={};users.forEach(u=>{const m=u.createdAt?.toDate?u.createdAt.toDate().toISOString().slice(0,7):'Unknown';reg[m]=(reg[m]||0)+1});chart('monthlyRegistrations','bar',Object.keys(reg),Object.values(reg));chart('activeInactive','doughnut',['Active','Inactive','Pending','Rejected'],['active','inactive','pending','rejected'].map(s=>users.filter(u=>u.status===s).length));chart('platformSavings','line',labels,users.map(u=>u.totalSavings));chart('platformExpenses','bar',labels,users.map(u=>u.totalExpenses))}
function renderAll(){renderCards();renderApprovals();renderUsers();renderCharts();renderAudit()}
async function approvalHistory(target,action){await addDoc(collection(db,'users',target,'approvalHistory'),{action,by:me.email,createdAt:serverTimestamp()}).catch(()=>{})}
window.approveUser=async id=>{await updateDoc(doc(db,'users',id),{approved:true,status:'active',approvedAt:serverTimestamp(),approvedBy:me.uid});await approvalHistory(id,'approved');const u=users.find(x=>x.id===id);await sendEmail('approved',{to_email:u?.email,name:u?.name});await log('Approval',{target:id});toast('User approved');loadUsers()};
window.rejectUser=async id=>{await updateDoc(doc(db,'users',id),{approved:false,status:'rejected',rejectedAt:serverTimestamp(),rejectedBy:me.uid});await approvalHistory(id,'rejected');const u=users.find(x=>x.id===id);await sendEmail('rejected',{to_email:u?.email,name:u?.name});await log('Rejection',{target:id});toast('User rejected');loadUsers()};
window.toggleUser=async id=>{const u=users.find(x=>x.id===id);if(u.email?.toLowerCase()===SUPER_ADMIN_EMAIL.toLowerCase())return toast('Super Admin cannot be changed',true);const active=u.status==='active';await updateDoc(doc(db,'users',id),{status:active?'inactive':'active',approved:!active,updatedAt:serverTimestamp()});await approvalHistory(id,active?'deactivated':'activated');await log(active?'Deactivate User':'Activate User',{target:id});loadUsers()};
window.deleteUserRow=async id=>{const u=users.find(x=>x.id===id);if(u.email?.toLowerCase()===SUPER_ADMIN_EMAIL.toLowerCase())return toast('Super Admin cannot be deleted',true);if(confirm('Delete this Firestore user document? Firebase Auth deletion requires Admin SDK/Cloud Function.')){await deleteDoc(doc(db,'users',id));await log('Delete User',{target:id});loadUsers()}};
window.viewUser=async id=>{const u=users.find(x=>x.id===id);const names=['income','expenses','goals','budgets','recurring','statements'];const counts={};for(const n of names){counts[n]=(await getDocs(collection(db,'users',id,n)).catch(()=>({docs:[]}))).docs.length}$('#userDetail').innerHTML=`<h3>${safe(u.name)}</h3><p>${safe(u.email)} • ${safe(u.role)} • ${safe(u.status)}</p><div class="cards grid">${names.map(n=>`<div class="card"><h3>${n}</h3><div class="value">${counts[n]}</div></div>`).join('')}</div><p class="muted">Income ${money(u.totalIncome)} • Expenses ${money(u.totalExpenses)} • Savings ${money(u.totalSavings)}</p>`;await log('View User Detail',{target:id})};
$('#createAdmin').onclick=()=>{if(!isSuper())return toast('Only Super Admin can create Admin users',true);$('#adminModal').classList.add('show')};$('#closeAdminModal').onclick=()=>$('#adminModal').classList.remove('show');
$('#adminCreateForm').onsubmit=async e=>{e.preventDefault();if(!isSuper())return toast('Only Super Admin can create Admin users',true);const email=$('#newAdminEmail').value.trim().toLowerCase(),pass=$('#newAdminPassword').value,name=$('#newAdminName').value.trim();const cred=await createUserWithEmailAndPassword(auth,email,pass);await setDoc(doc(db,'users',cred.user.uid),{name,email,role:'admin',approved:true,status:'active',createdAt:serverTimestamp(),createdBy:me.uid});await log('Create Admin',{email});$('#adminModal').classList.remove('show');toast('Admin created');loadUsers()};
$$('.nav-link[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#themeToggle').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('finoraTheme',document.body.classList.contains('light')?'light':'dark');renderCharts()};if(localStorage.finoraTheme==='light')document.body.classList.add('light');$('#logoutBtn').onclick=async()=>{await log('Logout');await signOut(auth);location.href='index.html'};$('#userSearch').oninput=renderUsers;$('#userFilter').onchange=renderUsers;
if(!hasConfig){toast('Firebase config missing. Add keys in firebase-config.js.',true); throw new Error('Firebase configuration missing');}
onAuthStateChanged(auth,async u=>{if(!u){location.href='index.html';return}me=u;const s=await getDoc(doc(db,'users',u.uid));if(!s.exists()){location.href='index.html';return}meData=s.data();if(!['admin','super_admin'].includes(meData.role)||!meData.approved||meData.status!=='active'){location.href='dashboard.html';return}$('#adminLine').textContent=`${meData.name||u.email} • ${meData.role}`;await loadUsers()});
